Added ability to modify MongoDB host and port, along with dynamic configuration generation.

diff --git a/hpfeeds-broker.run.j2 b/hpfeeds-broker.run.j2
--- a/hpfeeds-broker.run.j2
+++ b/hpfeeds-broker.run.j2
@@ -2,22 +2,31 @@
 
 source {{ sysconfig_dir }}/hpfeeds
 
-if [[ -z $MONGOIP ]]
-then
-  MONGOIP='127.0.0.1'
-fi
+cd {{ broker_dir }}
 
-if [[ -z $MONGOPORT ]]
+if [[ ! -f ./config.py ]]
 then
-  MONGOPORT=27017
-fi
+    if [[ ! -z $MONGODB_HOST ]]
+    then
+      MONGODB_HOST="--mongo_host ${MONGODB_HOST}"
+    else
+      MONGODB_HOST=""
+    fi
 
-# We can't really do anything but find/replace, or we have to fork upstream
-sed -i "s/MONGOIP = .*/MONGOIP = '${MONGOIP}'/" /opt/hpfeeds/broker/feedbroker.py
-sed -i "s/MONGOPORT = .*/MONGOPORT = ${MONGOPORT}/" /opt/hpfeeds/broker/feedbroker.py
+    if [[ -z $MONGOPORT ]]
+    then
+      echo "MongoDB port is required"
+      exit 1
+    else
+      MONGODB_PORT="--mongo_port ${MONGODB_PORT}"
+    fi
+
+    # We can't really do anything but find/replace, or we have to fork upstream
+    python generateconfig.py unattended ${MONGODB_HOST} ${MONGODB_PORT}
+fi
 
 echo "Starting hpfeeds..."
-echo "MONGOPIP = ${MONGOIP}"
-echo "MONGOPPORT = ${MONGOPORT}"
+echo "MONGODB_HOST = ${MONGODB_HOST}"
+echo "MONGODB_PORT = ${MONGODB_PORT}"
 
 exec /usr/bin/env python /opt/hpfeeds/broker/feedbroker.py
